services:
  myapp:
    build: ./app
    volumes:
      - ./app:/app
    ports:
      - "7000:4000"
    command: ["python3", "src/app.py"]
    
  adminer:
    image: adminer:4.6.2
    ports:
      - "8080:8080"

