services:
  myapp:
    build: ./app
    volumes:
      - ./app:/app
    ports:
      - "7000:4000"
    command: ["python3", "src/app.py"]

  adminer:
    build: ./app/adminer
    volumes:
      - ./app:/app
    ports:
      - "8080:8080"
    #entrypoint: ["php", "/app/adminer-4-sqlite3/index.php"]

