FROM python:3.8-alpine

RUN apk add --no-cache python3-dev  \
    && pip3 install --upgrade pip \
    && apk --no-cache add sqlite \
    && apk --no-cache add nano

WORKDIR /app

COPY . /app

RUN pip3 --no-cache-dir install -r requirements.txt

CMD ["python3", "src/app.py"]